services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker_password"
      MYSQL_DATABASE: "chronicle"
      TZ: "Asia/Tokyo"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $MYSQL_USER -p $MYSQL_PASSWORD
